### ISSUE TITLE
Standard Storage Request

### ISSUE THREAD

**Issue by emresaracoglu** [ToshY/BunnyNet-PHP#41]
Hello,

I'm not having any problems with Edge, but unfortunately, I can't upload files to a standard server. Is it possible to upload files to standard storage? 

Thank you

**Comment by ToshY** [comment]
Hey @emresaracoglu 👋 

Could you clarify on what you mean with upload files to a "standard server"? At this moment I'm only aware of the so-called "Edge Storage" Bunny.net is providing.

In order to understand the problem I need to have additional information or a code example of what exactly you're trying to do achieve.

**Comment by emresaracoglu** [comment]
I realized that it was caused by an error in my framework. I took your time, sorry

**Comment by ToshY** [comment]
No problem 🙂 Glad you've solved your issue.
