### ISSUE TITLE
Create Collection wrong endpoint

### ISSUE THREAD

**Issue by soixt** [ToshY/BunnyNet-PHP#48]
Needed to go deep to find it since I got no explanations from errors 🗡️ 

`"exception":"[object] (ArgumentCountError(code: 0): 3 arguments are required, 2`

Get this error on `createCollection($libraryId, $body)` where it calls for `CollectionEndpoint::CREATE_COLLECTION`

That uses: `'path' => 'library/%d/collections/%s',` however the api doesn't use second parameter so you should just remove `/%s`.

Here is a fix if you want to merge it: https://github.com/ToshY/BunnyNet-PHP/pull/49

@ToshY cheers

**Comment by ToshY** [comment]
Hey @soixt 👋 

Thanks for taking the time to create a bug report. The fix you've supplied seems fine, as I apparently seem to have fixed this in my feature branch (#47) as well.

I will however change the target branch to `2.x` instead of `master` and tag a new patch release. For your information, I will no longer actively maintain the `2.x` branch myself after the next major release (see #47).

Can I ask you what PHP version are you currently using for your project(s)?
